tasks:
  - init: npm install
    command: npm start
ports:
  - port: 8080
    onOpen: open-browser
image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
vscode:
  extensions:
    - vscode.npm@1.54.1:/AThKM/3ebmHR4rk85K6Gg==